# Copyright (c) 2015 Aaron Nash
# This source file is licensed under the terms of the "GPL (v2)" license.
# Please see the file LICENSE.md included in this distribution for licensing
# terms.

all: 
	gcc -o pp src/pp.c -lgphoto2
